### ISSUE TITLE
l'embed video passe sous les images

### ISSUE THREAD

**Issue by louis-ev** [arnaudjuracek/neomateriality#1]
![image](https://cloud.githubusercontent.com/assets/1948417/9978185/3c480b70-5f23-11e5-9acc-9abd5c5528d3.png)

**Comment by louis-ev** [comment]
lgtm

**Comment by arnaudjuracek** [comment]
:+1:

**Comment by louis-ev** [comment]
C'est pas une heure pour pusher des commits ! Pas une heure pour créer des issues non plus, cela dit.
